name: flysystem-bundle

on:
    pull_request: ~
    push:
        branches:
            - 1.x
            - 2.x
            - 3.x

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  coverage: none
                  tools: php-cs-fixer
            - name: php-cs-fixer
              run: |
                  php-cs-fixer fix --dry-run --diff

    phpunit:
        name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
        runs-on: ubuntu-latest
        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

        strategy:
            matrix:
                php-version:
                    - '8.4'
                symfony-version:
                    - '5.4.*'
                    - '6.4.*'
                    - '7.3.*'
                    - '7.4.*'
                    - '8.0.*'
                include:
                    - php-version: '8.0'
                      symfony-version: '5.4.*'
                    - php-version: '8.2'
                      symfony-version: '6.4.*'
                    - php-version: '8.2'
                      symfony-version: '7.3.*'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install PHP with pcov
              uses: shivammathur/setup-php@v2
              with:
                coverage: none
                php-version: ${{ matrix.php-version }}
                tools: flex

            - name: Remove incompatible packages
              if: matrix.symfony-version == '8.0.*'
              run: |
                  composer remove --no-update --dev doctrine/mongodb-odm

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                dependency-versions: highest

            - name: Run PHPUnit
              run: vendor/bin/simple-phpunit
